# Generated by Django 5.1.4 on 2025-01-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0002_usershelter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Домашнее', 'Домашнее'), ('Дикое', 'Дикое'), ('Экзотическое', 'Экзотическое')], max_length=50)),
                ('family', models.CharField(choices=[('Кошки', 'Кошки'), ('Собаки', 'Собаки'), ('Грызуны', 'Грызуны'), ('Птицы', 'Птицы'), ('Рептилии', 'Рептилии'), ('Другое', 'Другое')], max_length=50)),
                ('breed', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=50)),
                ('size', models.CharField(choices=[('Крупный', 'Крупный'), ('Средний', 'Средний'), ('Мелкий', 'Мелкий')], max_length=50)),
                ('arrival_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='pet_photos/')),
                ('shelter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterapp.shelter')),
            ],
        ),
    ]
