# Generated by Django 5.1.4 on 2025-01-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0003_pet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('Кошки', [('Сиамская', 'Сиамская'), ('Мейн-кун', 'Мейн-кун'), ('Сфинкс', 'Сфинкс')]), ('Собаки', [('Немецкая овчарка', 'Немецкая овчарка'), ('Такса', 'Такса'), ('Французский бульдог', 'Французский бульдог')]), ('Грызуны', [('Хомяк', 'Хомяк'), ('Крыса', 'Крыса'), ('Морская свинка', 'Морская свинка')]), ('Птицы', [('Попугай', 'Попугай'), ('Канарейка', 'Канарейка'), ('Волнистый попугайчик', 'Волнистый попугайчик')]), ('Рептилии', [('Игуана', 'Игуана'), ('Удав', 'Удав'), ('Черепаха', 'Черепаха')]), ('Другое', [('Другое', 'Другое')])], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=50),
        ),
    ]
