# Generated by Django 5.1.4 on 2025-01-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0010_alter_pet_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='family',
            field=models.CharField(choices=[('Домашнее', [('Кошки', 'Кошки'), ('Собаки', 'Собаки'), ('Парнокопытные', 'Парнокопытные'), ('Непарнокопытные', 'Непарнокопытные'), ('Фретка', 'Фретка'), ('Кролик', 'Кролик'), ('Грызуны', 'Грызуны'), ('Птицы', 'Птицы')]), ('Дикое', [('Псовые', 'Псовые'), ('Медвежьи', 'Медвежьи')])], max_length=50),
        ),
    ]
