# Generated by Django 5.1.4 on 2025-01-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0011_alter_pet_family'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Питомец', 'verbose_name_plural': 'Питомцы'},
        ),
        migrations.AlterField(
            model_name='pet',
            name='arrival_date',
            field=models.DateField(verbose_name='Дата появления в приюте'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=50, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('Домашнее', 'Домашнее'), ('Дикое', 'Дикое')], max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='family',
            field=models.CharField(max_length=50, verbose_name='Семейство'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=10, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Кличка'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/', verbose_name='Фото питомца'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('Крупный', 'Крупный'), ('Средний', 'Средний'), ('Мелкий', 'Мелкий')], max_length=10, verbose_name='Размер'),
        ),
    ]
