# Generated by Django 5.1.4 on 2025-01-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0012_alter_pet_options_alter_pet_arrival_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={},
        ),
        migrations.AlterField(
            model_name='pet',
            name='arrival_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(choices=[('Кошки', [('Сиамская', 'Сиамская'), ('Мейн-кун', 'Мейн-кун'), ('Сфинкс', 'Сфинкс')]), ('Собаки', [('Немецкая овчарка', 'Немецкая овчарка'), ('Такса', 'Такса'), ('Французский бульдог', 'Французский бульдог')]), ('Грызуны', [('Хомяк', 'Хомяк'), ('Крыса', 'Крыса'), ('Морская свинка', 'Морская свинка')]), ('Птицы', [('Попугай', 'Попугай'), ('Канарейка', 'Канарейка'), ('Волнистый попугайчик', 'Волнистый попугайчик')]), ('Рептилии', [('Игуана', 'Игуана'), ('Удав', 'Удав'), ('Черепаха', 'Черепаха')]), ('Другое', [('Другое', 'Другое')])], max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='category',
            field=models.CharField(choices=[('Домашнее', 'Домашнее'), ('Дикое', 'Дикое'), ('Экзотическое', 'Экзотическое')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='family',
            field=models.CharField(choices=[('Кошки', 'Кошки'), ('Собаки', 'Собаки'), ('Грызуны', 'Грызуны'), ('Птицы', 'Птицы'), ('Рептилии', 'Рептилии'), ('Другое', 'Другое')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pet',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='pet_photos/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('Крупный', 'Крупный'), ('Средний', 'Средний'), ('Мелкий', 'Мелкий')], max_length=50),
        ),
    ]
