# Generated by Django 5.1.4 on 2025-01-31 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0016_vetassignment_alter_pet_breed_alter_pet_family_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='vet_assignment',
        ),
    ]
