# Generated by Django 5.1.4 on 2025-02-06 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelterapp', '0017_remove_pet_vet_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetVetAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterapp.pet')),
                ('vet_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelterapp.vetassignment')),
            ],
            options={
                'unique_together': {('pet', 'vet_assignment')},
            },
        ),
        migrations.AddField(
            model_name='pet',
            name='vet_assignments',
            field=models.ManyToManyField(related_name='pets', through='shelterapp.PetVetAssignment', to='shelterapp.vetassignment'),
        ),
    ]
